# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
  - smartcontractkit/chainlink-brownie-contracts@0.4.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'

# automatically fetch contract sources from Etherscan
autofetch_sources: True
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: False
  kovan:
    verify: False
  ganache:
    verify: False

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}

